name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies on pokerogue
        uses: bahmutov/npm-install@v1
        with:
          working-directory: pokerogue

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Pre build
        run: node ./pre-build.js

      - name: Build pokerogue
        run: npm run build
        working-directory: pokerogue

      - name: Pre build
        run: node ./post-build.js

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Build project
        run: npm run tauri build

      - name: Pre release
        run: node ./release.js

      - name: Get version
        id: get_version
        run: echo "::set-output name=version::$(cat VERSION)"

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./src-tauri/target/release/pokerogue.exe"
          bodyFile: "body.md"
          tag: ${{ steps.get_version.outputs.version }}
          token: ${{ secrets.YOUR_GITHUB_TOKEN }}
