name: Release

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    uses: ./.github/workflows/workflow-release.yml
    secrets:
      token: ${{ github.token }}
