name: Sync Release

on:
  #schedule:
  #  - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  sync:
    uses: ./.github/workflows/workflow-sync-release.yml
  release:
    uses: ./.github/workflows/workflow-release.yml
    needs: sync
    if: ${{ needs.sync.outputs.outcome == 'success' }}

